config/routes.rb
GgMrp::Application.routes.draw do
  devise_for :users
  root :to => 'builds#index'
  resources :builds #, :has_many => [:parts]
  resources :suppliers #, :has_many => [:parts]
  
  resources :builds do
    resources :uses
  end
  resources :suppliers do
    resources :parts
  end
  

  
  match '*a', :to => 'errors#invalid_route'
end

app/models/build.rb
class Build < ActiveRecord::Base
  attr_accessible :name, :gg_id, :ext_id, :due_by, :description
  has_many :parts, :dependent => :destroy
  
  
  before_save '!(self.name.empty? or blacklisted_value? self.name)'
end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :name, :gg_id, :ext_id, :supplier, :description
  
  # instance methods
  def validated_save
    if self.name.empty? or blacklisted_value? self.name
      # refuse to save
      return false
    else
      # save to db
      return self.save
    end
  end
  def blacklisted_value? (value)
    # these are reserved and will cause bugs if used
    if    value== 'sort_by'
    elsif value== 'utf8'
    elsif value== 'commit'
    else
      return false
    end
    return true
  end
  # class methods
  def self.attrs
    return Part.accessible_attributes
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name, :gg_id, :description, :phone, :email,
              :address0, :address1, :address2, :address3, :address4
  has_many :parts
  
  before_save '!(self.name.empty? or blacklisted_value? self.name)'
end

app/models/use.rb
=begin
class Use < ActiveRecord::Base
  attr_accessible :name, :gg_id, :ext_id, :supplier, :lead_time, :description
  belongs_to :part
  #belongs_to :part
  belongs_to :build, polymorphic: true
  belongs_to :supplier
  
  before_save '!(self.name.empty? or blacklisted_value? self.name)'
  

end
=end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  # rails 4.x code
  #before_action :authenticate_user!, :except => [:index, :show]
  # rails 3.x code
  before_filter :authenticate_user!
  # database CRUD actions below
  def create
    @build= Build.new
    fill_attribs_by_hash! @build, params[:build]
    action_notify @build.name, @build.validated_save
  end
  def show
    @build= Build.find_by_id(params[:id])
    @parts= Part.all
  end
  def update
    @build= Build.find_by_id(params[:id])
    fill_attribs_by_hash! @build, params
    action_notify @build.name, @build.validated_save
  end
  def destroy
    @build= Build.find_by_id(params[:id])
    action_notify @build.name, @build.destroy
  end
  # CRUD accessories
  def new
    # no information to feed view
  end
  def edit
    @build= Build.find_by_id(params[:id])
  end 
  def index
    
    @sorted_by_user= false
    # send to view
    @builds= Build.all
  end
  # other routes
  def action_
    raise
  end
  # methods without URI routing assigned
  def action_notify(name, flag)
    flash.notice= name.to_s
    if flash.notice.length < 1
      flash.notice= 'Database entry'
    end
    action= caller[0][/`([^']*)'/, 1] #name of the method that called this one
    unless action.last(1)== 'e'
      action+= 'e' #append an e on the end of words not ending in e
    end
    if flag
      flash.notice+= ' has been ' + action.to_s + 'd.'
    else
      flash.notice+= ' was NOT ' + action.to_s + 'd!'
    end
    redirect_to builds_path(), :method => :get
  end
  def fill_attribs_by_hash! (model_instance_object, hash)
    model_instance_object.class.accessible_attributes.each { |attr|
      unless attr.empty?
        eval (%{
          if hash.has_key? "#{attr}"
            if model_instance_object.respond_to? "#{attr}="
              model_instance_object.#{attr}= hash["#{attr}"]
            end
          end
        })
      end
    }
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def invalid_route
    # user followed an invalid or outdated URI
    message= 'Sent to Home Page instead of invalid URI: '
    message+= request.original_url
    flash.keep
    if flash[:notice].empty?
      flash[:notice]= message
    elsif flash[:warning].empty?
      flash[:warning]= message
    else
      flash[:notice]+= "\n"+ message
    end
    redirect_to builds_path(), :method => :get
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
# rails 4.x code
  #before_action :authenticate_user!, :except => [:index, :show]
  # rails 3.x code
  before_filter :authenticate_user!
  # database CRUD actions below
  def create
    @part= Part.new
    fill_attribs_by_hash! @part, params[:part]
    action_notify @part.name, @part.validated_save
  end
  def show
    @part= Part.find_by_id(params[:id])
  end
  def update
    @part= Part.find_by_id(params[:id])
    fill_attribs_by_hash! @part, params
    action_notify @part.name, @part.validated_save
  end
  def destroy
    @part= Part.find_by_id(params[:id])
    action_notify @part.name, @part.destroy
  end
  # CRUD accessories
  def new
    # no information to feed view
  end
  def edit
    @part= Part.find_by_id(params[:id])
  end 
  def index
    @sorted_by_user= false
    # send to view
    @parts= Part.all
  end
  # other routes

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  # database CRUD actions below

end

app/controllers/uses_controller.rb
=begin
class UsesController < ApplicationController
  # rails 4.x code
  #before_action :authenticate_user!, :except => [:index, :show]
  # rails 3.x code
  before_filter :authenticate_user!
  before_filter :lookup_build
  def lookup_build
    @build= Build.find_by_id(params[:build_id]) ||
      redirect_to builds_path,
        :flash => {:alert => 'build_id not found in URI parameters'}
    @part= Part.find_by_id(params[:part_id]) ||
      redirect_to parts_path,
        :flash => {:alert => 'part_id not found in URI parameters'}
  end
  # database CRUD actions below
  def create
    @use= Use.new
    fill_attribs_by_hash! @use, params[:use]
    action_notify @use.name, @use.validated_save
  end
  def show
    @use= Use.find_by_id(params[:id])
    #@parts= Part.all
  end
  def update
    @use= Use.find_by_id(params[:id])
    fill_attribs_by_hash! @use, params
    action_notify @use.name, @use.validated_save
  end
  def destroy
    @use= Build.find_by_id(params[:id])
    action_notify @use.name, @use.destroy
  end
  # CRUD accessories
  def new
    # no information to feed view
  end
  def edit
    @use= Use.find_by_id(params[:id])
  end 
  def index
    
    @sorted_by_user= false
    # send to view
    @uses= Use.all
  end
  # other routes
  def action_
    raise
  end
end
=end

app/helpers/application_helper.rb
module ApplicationHelper
  # instance methods
  def full_title(page_title)
    # returns the full title or a specific one
    base_title= 'GG-MRP'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  def blacklisted_value? (value)
    # these are reserved and will cause bugs if used
    ['sort_by', 'utf8', 'commit'].include? value
  end
end
class ActiveRecord::Base
  def to_param
    #override rails' default behaviour for prettier uris while still retaining the :id
    "#{self.id}-#{self.name.parameterize}"
  end
  def attrs
    #shortcut to default behaviour
    self.class.accessible_attributes
  end
  # class methods
  def self.attrs
    #shortcut to default behaviour
    self.accessible_attributes
  end
end

app/views/builds/index.html.haml
-#%h2=link_to 'Builds List', builds_path, :class => :link, :id => :all_builds_link
%table#builds
  %thead
    %tr
      - Build.attrs.each do |attr|
        -unless attr.empty?
          - if @sort_by== attr
            - if @sorted_by_user
              %th.hilite= attr
            - else
              %th= attr
          - else
            %th= eval("link_to attr.to_s.titleize, builds_path(:sort_by => attr), :method => :get, :class => :link, :id => :#{attr.to_s}_header")
      %th More
  %tbody
    - @builds.each do |build|
      %tr
        - Build.attrs.each do |attr|
          - unless attr.empty?
            -# if attr== 'description'
              -#%td= link_to "More about #{build.name}", build_path(build), :class => :more_info_link
            -# else
              -#%td= eval(%Q{if build.respond_to? "#{attr}" then build.#{attr} else '' end})
            %td= eval(%Q{if build.respond_to? "#{attr}" then build.#{attr} else '' end})
        %td= link_to "More about #{build.name}", build_path(build), :class => :more_info_link
= link_to 'Create new build', new_build_path, :method => :get, :class => :link, :id => :new_build_link
%br
= link_to 'Reset filter and sort settings', builds_path(:session_type => :new), :method => :get, :class => :link, :id => :reset_session

app/views/builds/new.html.haml
- provide(:title, 'New Build')
%h2 Create new build
= form_tag builds_path do
  %table#new_build
    %thead
      %tr#labels
        - Build.attrs.each do |attr|
          - unless attr.empty?
            %th= attr.to_s
    %tbody
      %tr#fields
        - Build.attrs.each do |attr|
          - unless attr.empty?
            %td.title= text_field :build, attr.to_s
  = submit_tag 'Save', :name => 'user_selection'
= link_to 'Back to Index', builds_path, :method => :get

app/views/builds/show.html.haml
- provide(:title, @build.name)
%table#build_table
  %thead
    %tr
      - @build.attrs.each do |attr|
        - unless attr.empty?
          %td= attr.titleize
  %tbody
    %tr
      - @build.attrs.each do |attr|
        - unless attr.empty?
          %td= eval("@build.#{attr.to_s}")
%br
%br
= "Parts in #{@build.name}:"
%br
%table#parts_table
  %thead
    %tr
      - Part.attrs.each do |attr|
        - unless attr.empty?
          %td= attr.titleize
  %tbody
    - @parts.each do |part|
      %tr
        - Part.attrs.each do |attr|
          - unless attr.empty?
            %td= eval("part.#{attr.to_s}")
=# link_to "Remove part from #{@build.name}", new_part_path {{no new part path}}(:build_id => @build.id), :method => :get, :class => :link, :id => :new_part_link

%br
%br
=# collection_select :part, :build_id, Part.all, :id, :name, :prompt => :true


%br
%br

%br
%br
= "All Parts:"
%br
%table#parts_table
  %thead
    %tr
      - Part.attrs.each do |attr|
        - unless attr.empty?
          %td= attr.titleize
  %tbody
    - @parts.each do |part|
      %tr
        - Part.attrs.each do |attr|
          - unless attr.empty?
            %td= eval("part.#{attr.to_s}")
=# @build.id
=# link_to "Add part to #{@build.name}", new_part_path {{no new part path}} (:build_id => @build.id), :method => :get, :class => :link, :id => :new_part_link

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'/>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="header">
      <p class="notice">
        <%- unless flash.notice.to_s.length < 1 %>
          <h2><%= flash.notice %></h2>
          <br /><br />
        <%- end %>
      </p>
      <p class="alert">
        <%- unless flash.alert.to_s.length < 1 %>
          <h1><%= flash.alert %></h1>
          <br /><br />
        <%- end %>
      </p>
      <div id= "navbar">
        <%= link_to "Home", builds_path %>
        <%- if user_signed_in? %>
          <%= link_to "Account: "+ current_user.email, edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <%- else %>
          <%= link_to "Create a new account", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        <%- end %>
      </div>
    </div>
    <div id="main_body">
      <%= yield %>
    </div>
    <br/>
    <br/>
    <br/>
    <div id="footer">
      <%= link_to (image_tag 'HTML5.png', :alt => 'HTML5', :style => 'border:0;height:20px'), ('http://validator.w3.org/check?uri=' + request.original_url) %>
      <%= link_to (image_tag 'w3c_home.gif', :alt => 'W3C', :style => 'border:0;height:20px'), ('http://validator.w3.org/check?uri=' + request.original_url) %>
    </div>
  </body>
</html>